### ISSUE TITLE
Getting error while start bchnode

### ISSUE THREAD

**Issue by 1notchdev** [owstack/bcccore-node#27]
![screen shot 2017-12-13 at 8 11 38 am](https://user-images.githubusercontent.com/3859898/33924144-5eccae8e-dfdd-11e7-8ead-97f5fc498f24.png)

**Comment by niahmiah** [comment]
Hi. It looks like your error is related to the protocol being used in your RPC connection. If you can provide your conf file, I may be able to spot the issue...

**Comment by achakhalyan** [comment]
I have get same error before start bchnode 
[2018-01-27T19:59:50.718Z] info: Using config: /home/armen/.bch/bch-node.json
[2018-01-27T19:59:50.720Z] info: Using network: livenet
[2018-01-27T19:59:50.721Z] info: Starting bitcoind
[2018-01-27T19:59:50.723Z] info: Using bitcoin config file: /home/armen/.bch/data/bitcoin.conf
[2018-01-27T20:04:46.201Z] error: Failed to start services
[2018-01-27T20:04:46.204Z] error: RPCError: Bitcoin JSON-RPC: Request Error: connect ECONNREFUSED 127.0.0.1:8332
    at Bitcoin._wrapRPCError (/home/armen/.nvm/versions/node/v4.8.7/lib/node_modules/@owstack/bch-node/lib/services/bitcoind.js:447:13)
    at /home/armen/.nvm/versions/node/v4.8.7/lib/node_modules/@owstack/bch-node/lib/services/bitcoind.js:779:28
    at newCallback (/home/armen/.nvm/versions/node/v4.8.7/lib/node_modules/@owstack/bch-node/node_modules/@owstack/bitcoind-rpc/lib/index.js:52:16)
    at ClientRequest.<anonymous> (/home/armen/.nvm/versions/node/v4.8.7/lib/node_modules/@owstack/bch-node/node_modules/@owstack/bitcoind-rpc/lib/index.js:136:7)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:269:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1272:8)
[2018-01-27T20:04:46.204Z] info: Beginning shutdown
[2018-01-27T20:04:46.206Z] info: Stopping web (not started)
[2018-01-27T20:04:46.206Z] info: Stopping bitcoind
[2018-01-27T20:04:46.207Z] info: Halted


its a my config file 
server=1
whitelist=127.0.0.1
txindex=1
addressindex=1
timestampindex=1
spentindex=1
zmqpubrawtx=tcp://127.0.0.1:28332
zmqpubhashblock=tcp://127.0.0.1:28332
rpcallowip=127.0.0.1
rpcuser=bitcoin
rpcpassword=local321
uacomment=bch

**Comment by niahmiah** [comment]
Hey guys. Sorry, this project is rather new and still lacking docs, but we are aiming to be used via Docker.

Here is a relevant section of docker-compose.yml for running a BCH stack

```
  bitcoin-abc:
    image: "owstack/bitcoin-abc:0.16.0-ows"
    user: root
    command: "/usr/local/bin/bitcoind -datadir=/data -printtoconsole"
    ports:
      - "8339:8332"
      - "28339:28332"
    volumes:
      - /data/bitcoin-abc:/data
  bch-node:
    image: owstack/bch-node:v0.0.11-beta2
    ports:
      - "3009:3001"
    #   - "3232:3232"
    depends_on:
      - "bitcoin-abc"
    volumes:
      - /data/bch-node:/home/ows/config
    command: "bchnode start -c /home/ows/config -m /home/ows/bitcoin-cash-services"
```

Note that this mounts a local /data/bch-node directory into the docker image as /home/ows/config

In that directory, place your bch-node.json file, like this one:

```
{
  "network": "livenet",
  "port": 3001,
  "services": [
    "explorer",
    "explorer-api",
    "bitcoind",
    "web"
  ],
  "servicesConfig": {
    "bitcoind": {
      "connect": [{
        "zmqpubrawtx": "tcp://bitcoin-abc:28332",
        "zmqpubhashblock": "tcp://bitcoin-abc:28332",
        "rpcprotocol": "http",
        "rpchost": "bitcoin-abc",
        "rpcport": 8332,
        "rpcuser": "bitcoin",
        "rpcpassword": "local321"
      }]
    },
    "explorer-api": {
      "module": "@owstack/bch-explorer-api",
      "apiPrefix": "explorer-api",
      "disableRateLimiter": true
    },
    "explorer": {
      "module": "@owstack/ows-explorer"
    }
  }
}
```

You would also mount your config for your bitcoind container in a similar manner.

We'll work towards documenting this soon, and fixing the default config files.
